### PR TITLE
webserver: add "Restart=always" for rsyncd, phabricator, tessera, gollum

### PR DESCRIPTION
**Pull request by oliver**
This ensures that the services are automatically restarted if they crash or
are killed by OOM killer.

Also, set "RestartSec=5" to avoid too quick restarts during temporary
system problems.

### CODE REVIEW

**Comment by genofire** [comment]
Oh nice we migrate from Supervisor to systemd (for tiles) ...
Looks okay for me - but i am not the maintainer of the webserver roles ...

**Comment by jplitza** [comment]
I am not a fan of Restart=always without probable cause. The tile server might actually die because of memory limits, but rsyncd for example probably is stable AF.

**Comment by ghost** [comment]
Set for tile server and kick the rest. Then merge.

**Comment by ghost** [comment]
Fixed the issue. Will merge

**Pull request merged**
